local testPath = debug.getinfo(1, "S").source:match("^@(.*/)")
local fixture = dofile(testPath .. "workspace_panel_fixture.lua")
local previousHs, assertions = hs, 0
local function equal(actual, expected, label)
  assertions = assertions + 1
  assert(actual == expected, label .. ": expected " .. tostring(expected) .. ", got " .. tostring(actual))
end
local function open(names)
  local f = fixture.new(); f:seed(names)
  f.workspace.restoreWorkspace = function(_, name, options) table.insert(f.restores, { name = name, context = options._context }) end
  f.workspace.establishWorkspace = function(_, name, options) table.insert(f.establishes, { name = name, context = options._context }) end
  return f, f:open()
end

local f, view = open()
equal(f:session().state, "library", "open saved layouts")
equal(#f:model().entries, 2, "show saved recipes")
equal(f:model().entries[1].name, "Alpha", "sort library by name")
equal(#f:model().entries[1].rectangles, 1, "existing recipes get previews without recapture")
equal(f.enumerations, 0, "opening library never captures desktop")
equal(f.writes, 0, "opening library never writes settings")
equal(#f.hotkeys, 0, "no panel hotkeys registered globally")
equal(view.content.name, "TheseusWorkspacePanel", "one local message bridge")
f:open()
equal(#f.views, 1, "repeat entry brings same native window forward")
f:send("delete", "Zeta")
equal(f:session().state, "confirm-delete", "deletion is inline")
equal(f:model().message:find("“Zeta”", 1, true) ~= nil, true, "confirm exact selected name, not row index")
equal(f.writes, 0, "requesting deletion does not delete")
f:send("restore", "Alpha"); f:send("establish", "Alpha"); f:send("delete", "Alpha")
equal(#f.restores, 0, "no restore while confirming")
equal(#f.establishes, 0, "no establish while confirming")
f:send("cancel")
equal(f:session().state, "library", "Cancel returns to library")
equal(f:model().selectedName, "Zeta", "Cancel retains selected target")
equal(f:recipe("Zeta") ~= nil, true, "Cancel preserves recipe")
f:send("delete", "Zeta"); f:send("confirm-delete")
equal(f:recipe("Zeta"), nil, "confirmed deletion removes exact target")
equal(f:recipe("Alpha") ~= nil, true, "confirmed deletion preserves sibling")
equal(f.writes, 1, "one durable deletion")
equal(#f:model().entries, 1, "refresh live previews after deletion")
equal(f.enumerations, 0, "deletion never enumerates project windows")
f:send("restore", "Alpha")
equal(f.restores[1].name, "Alpha", "Restore routes to existing engine")
equal(f.restores[1].context.spaceID, 901, "freeze operation destination before losing focus")
equal(f:session(), nil, "restore closes panel")
equal(view.deleted, true, "release native window")
equal(#f.hotkeys, 0, "no local gesture leaks into other apps")

f, view = open(); f:send("establish", "Zeta")
equal(f.establishes[1].name, "Zeta", "Establish routes to existing engine")
equal(#f.restores, 0, "Establish is not Restore")
equal(f.enumerations, 0, "dispatch does not move any windows itself")
equal(view.deleted, true, "Establish releases panel")

f, view = open({ 'Final "draft"' }); f:send("delete", 'Final "draft"'); f:send("confirm-delete")
equal(next(f.settings.TheseusWorkspaceRecipesV1.recipes), nil, "delete final recipe")
equal(f:session().state, "library", "keep empty window available for Capture")
equal(#f:model().entries, 0, "empty-state model")
equal(view.deleted, nil, "final deletion never closes or recreates the window")
f:send("delete", "Missing")
equal(f.writes, 1, "missing selection cannot delete anything")
f:send("capture"); f:drain()
equal(f:session().state, "ready", "capture from an empty catalog")

f = open(); f:send("delete", "Alpha"); f:recipe("Alpha").windows[1].frame.x = .25
f:send("confirm-delete")
equal(f.writes, 0, "stale confirmation preserves changed recipe")
equal(f:recipe("Alpha").windows[1].frame.x, .25, "preserve newer geometry")
equal(f:session().state, "library", "stale confirmation returns to library")
f:send("delete", "Alpha"); f.saveError = true; f:send("confirm-delete")
equal(f.writes, 0, "failed deletion is not persisted")
equal(f:recipe("Alpha") ~= nil, true, "failed write preserves saved recipe")
equal(f:model().error:find("could not save", 1, true) ~= nil, true, "inline settings error")

f, view = open(); local stale = view.content.callback; local revision = f:session().revision
f:send("delete", "Alpha"); f:send("confirm-delete", nil, revision)
equal(f.writes, 0, "ignore event queued before confirmation")
f.workspace:stop(); stale({ body = { action = "confirm-delete", revision = revision + 1 } })
equal(f.writes, 0, "stale closed session cannot delete")
equal(view.deleted, true, "stop releases window")
f:open(); stale({ body = { action = "restore", name = "Alpha", revision = 0 } })
equal(#f.restores, 0, "old session cannot operate replacement window")
equal(f:session().state, "library", "replacement remains usable")
f:send("close")
equal(f:session(), nil, "Escape-style close releases session")

f = open(); f.workspace._restoreOperation = { jobs = {}, report = {} }
f:send("establish", "Alpha")
equal(#f.establishes, 0, "reject overlapping Establish")
equal(f:session().state, "library", "busy operation leaves library usable")
f:send("capture")
equal(f.enumerations, 0, "do not capture windows while placements are pending")
f.workspace._restoreOperation = nil
f.spaceType = "fullscreen"; f:send("restore", "Alpha")
equal(#f.restores, 0, "reject incompatible destination before closing")
equal(f:session().state, "library", "invalid destination keeps window")

f = fixture.new(); f.openError = true; f:open()
equal(f:session(), nil, "opening failure leaves no active session")
equal(#f.alerts, 1, "opening failure has a useful alert")
f = fixture.new(); f.renderError = { description = "render failed" }; f:open()
equal(f:session().renderError, "render failed", "retain native JavaScript diagnostics")
f.renderError = { code = 0 }; f:session():render()
equal(f:session().renderError, nil, "native code-zero success clears stale diagnostics")
f.renderError = { code = 4, localizedDescription = "JavaScript exception" }; f:session():render()
equal(f:session().renderError, "JavaScript exception", "retain native localized error description")
f.renderError = nil; f:session():render()
equal(f:session().renderError, nil, "ordinary success clears stale diagnostics")
f.workspace:bindHotkeys({ workspaces = { { "ctrl", "alt", "cmd" }, "r" } })
equal(#f.hotkeys, 1, "only one reference global shortcut")
f.hotkeys[1].callback()
equal(#f.views, 1, "global command reuses panel")
f.workspace:stop()
equal(f.hotkeys[1].deleted, true, "stop cleans global entry shortcut")

hs = previousHs
print(string.format("workspace_panel_workflow_spec: %d assertions passed", assertions))
